### PR TITLE
Website finished

### PR DESCRIPTION
**Pull request by JQuezada0**
Check it

---

This change is [Review on Reviewable](https://reviewable.io/reviews/nw0428/sibspring2016/6)

### CODE REVIEW

**Comment by JQuezada0** [comment]
lgtm

**Comment by melissa0831** [comment]
lgtm

**Comment by jdorancy** [comment]
Looks really good!

**Comment by nw0428** [comment]
You got rid of both the index.html and my page!
FIXIT!!!!

**Pull request merged**
